version: '3.9'

services:
  task-app:
    image: task-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-app
    hostname: task-app
    ports:
      - "3000:3000"

  nginx:
    image: reverse-proxy 
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-c
    ports:
      - "80:80"
    depends_on:
      - task-app
